flags = {
    "Uruguay":'🇺🇾',
    "Netherlands": '🇳🇱',
    "Belgium": '🇧🇪',
    "France": '🇫🇷',
    "England":'🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    "Brazil":'🇧🇷',
    "Germany": '🇩🇪',
    "Argentina":'🇦🇷',
    "Switzerland": '🇨🇭',
    "Croatia": '🇭🇷',
    "Denmark":'🇩🇰',
    "Spain":'🇪🇸',
    "Mexico":'🇲🇽',
    "USA":'🇺🇸',
    "Portugal":'🇵🇹',
    "Senegal":'🇸🇳',
    "South Korea":'🇰🇷',
    "Morocco":'🇲🇦',
    "Serbia":'🇷🇸',
    "Japan":'🇯🇵',
    "Ecuador":'🇪🇨',
    "Tunisia":'🇹🇳',
    "Poland":'🇵🇱',
    "Iran":'🇮🇷',
    "Costa Rica":'🇨🇷',
    "Canada":'🇨🇦',
    "Cameroon":'🇨🇲',
    "Australia":'🇦🇺',
    "Saudi Arabia":'🇸🇦',
    "Wales":'🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    "Ghana":'🇬🇭',
    "Qatar":'🇶🇦',
    'Russia':'🇷🇺',
    'Egypt':'🇪🇬',
    'Peru':'🇵🇪',
    'Iceland':'🇮🇸',
    'Nigeria':'🇳🇬',
    'Sweden':'🇸🇪',
    'Korea Republic':'🇰🇷',
    'Panama':'🇵🇦',
    'Colombia':'🇨🇴',
    'Czechia':'🇨🇿',
    'Ukraine':'🇺🇦',
    'Romania':'🇷🇴',
    'Hungary':'🇭🇺',
    'Georgia':'🇬🇪',
    'Scotland':'🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'Albania':'🇦🇱',
    'Turkey':'🇹🇷',
    'Austria':'🇦🇹',
    'Slovenia':'🇸🇮',
    'Slovakia':'🇸🇰',
    'Italy':'🇮🇹',
}